service: email-sender

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    EMAIL_SENDER: tamannachoudhary8797@gmail.com
    PROFILE: Tamanna

custom:
  stage: ${opt:stage, 'dev'}
  offline:
    port: 3000
    stage: ${self:custom.stage}

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true


